### ISSUE TITLE
Bonus : Partage des graphs

### ISSUE THREAD

**Issue by Liliaze** [Hantlowt/HololensTrading#7]
Réaliser le 9ème tuto de l'hololens academy et s'en servir de base pour ajouter la possibilité de partager les graphiques avec un second casque.

**Comment by Hantlowt** [comment]
Pour aujourd'hui c'est chaud, mais y'a moyen de le faire dans le courant de la semaine prochaine je pense

**Comment by Liliaze** [comment]
Bonne avancée de Antoine ! Continue comme cela ;) !
